128 react router to diff game modes
abronstone/vaasle pull request #158
Opened 2023-11-13 03:58 UTC by spatino1234

Created the following js files to seperate out components, we have a working gamemode page, single & multiplayer page 

1. GameMode.js
2. Singleplayer.js
3. Multiplayer.js
4. Layout.js

2023-11-13 16:57 UTC, AidanRoessler requested changes
Looks good to me, thanks for getting this up and working. I haven't had the chance to run this branch myself because I'm waiting until after my interview just so I 100% guarantee that I have a stable build for the demo and don't mess up my Docker, but after that today I will run it. Please see my comments below

2023-11-13 17:07 UTC, spatino1234 commented on src/frontend/src/index.css
> +/* .gameMode-butons {
commented code has been deleted now

2023-11-13 17:07 UTC, spatino1234 commented on src/frontend/src/App.js
> +  // TODO replace this with multiple pages
removed

2023-11-13 22:17 UTC, AidanRoessler approved these changes
I'll approve this just so we can merge it in but I think we need a separate issue to refactor how we handle making a new game with multiple pages now. There are times when navigating away from the single player/multiplayer page and then coming back doesn't generate a new game, so the UI gets messed up and you can only see your 2nd to last guess in the bottom row, not your last guess. I can open an issue to do that because I wrote the logic.

2023-11-13 22:28 UTC, AidanRoessler requested changes
Working on this myself now...

2023-11-13 22:28 UTC, AidanRoessler commented on src/frontend/src/App.js
> +            <Singleplayer gameState={gameState} setGameState={setGameState} />
We need to call the` initalGameState()` call back function here so that we're not just creating a new game each time the user logs in or out

2023-11-14 01:51 UTC, AidanRoessler approved these changes

2023-11-14 01:53 UTC, merged